security:
    providers:
        app_user_provider:
            memory:
                users:
                    '*':
                        password: ''
                        roles: 'ROLE_USER'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\CookieAuthenticator

    access_control:
        - { path: ^/, roles: ROLE_USER } 